apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ctlptl-registry
port: 5000
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: kind-rebalancer-dev
product: kind
kubernetesVersion: v1.24.0
registry: ctlptl-registry