# permissions for end users to edit rebalances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rebalance-editor-role
rules:
- apiGroups:
  - rebalancer.ch1aki.github.io
  resources:
  - rebalances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rebalancer.ch1aki.github.io
  resources:
  - rebalances/status
  verbs:
  - get
