---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - rebalancer.ch1aki.github.io
  resources:
  - rebalances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rebalancer.ch1aki.github.io
  resources:
  - rebalances/finalizers
  verbs:
  - update
- apiGroups:
  - rebalancer.ch1aki.github.io
  resources:
  - rebalances/status
  verbs:
  - get
  - patch
  - update
