apiVersion: rebalancer.ch1aki.github.io/v1
kind: Rebalance
metadata:
  name: rebalance-sample
spec:
  dryRun: false
  rule:
    flactation:
      variation: "1"
      max: "10"
      min: "2"
    condition: "result[0]>=0"
    interval: 1m
  target:
    route53:
      hostedZoneID: exampleZoneID
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret
            key: access-key
          secretAccessKeySecretRef:
            name: aws-secret
            key: secret-access-key
      resource:
        name: www.example.com
        type: A
        identifier: www
  dataSource:
    prometheus:
      address: http://prometheus-kube-prometheus-prometheus.default.svc.cluster.local:9090
      auth:
        secretRef:
          userSecretRef:
            name: prom-secret
            key: user
          passwordSecretRef:
            name: prom-secret
            key: password
      timeout: 30
      query: |-
        avg(
          sum(
            rate(node_cpu_seconds_total{mode!="idle"}[5m])
          ) without (mode)
        )